version: '3.4'

x-common:
  # image: apache/airflow:2.3.0
  &common
  build: .
  user: "${AIRFLOW_UID}:0"
  env_file:
    - .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./files:/opt/airflow/files
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./app:/opt/airflow/app
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - default

x-depends-on:
  &depends-on
  depends_on:
    postgres:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully
  networks:
    - default

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - ./db_internal/data:/var/lib/postgresql/data
    networks:
      - default

  scheduler:
    <<: [ *common, *depends-on ]
    container_name: airflow-scheduler
    command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"
    networks:
      - default

  webserver:
    <<: [ *common, *depends-on ]
    container_name: airflow-webserver
    restart: always
    command: webserver
    ports:
      - "8090:8080"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8080/health"
        ]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - default

  airflow-init:
    <<: *common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins /sources/app
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins,app}
        exec /entrypoint airflow version
    networks:
      - default

networks:
  default:
    external:
      name: external-network

volumes:
  dados-datalake:
    external: true
