version: '3.4'
services:
  app-consumer:
    build: '.'
    networks:
      - default
    container_name: app-consumer
    ports:
      - "5000:5000"

networks:
    default:
      external:
        name: external-network


